runner:
  credo:
    cmd: mix credo suggest -a --strict --format=flycheck
    errorformat:
      - "%f:%l:%c: %t: %m"
      - "%f:%l: %t: %m"
    level: warning
    name: credo
  hadolint:
    cmd: hadolint Dockerfile
    errorformat:
      - "%f:%l %m"
    level: failure
    name: hadolint
